apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - uses: docker://golang:1.20.3-alpine3.17
        name: Say hello2
        shell: sh
        run: |
          echo "hello world 3"
      - uses: gha-swashbuck1r-run-workflow
        with:
          repo-name: simple-go-app
          branch-name: main
          workflow-name: github-actions-demo
          parameters: '{}'
